name: User Story
description: "Create a User Story"
assignees: gpalacios2001
labels: user-story
title: "User Story: "

body:
  - type: input
    id: problem
    validations:
      required: true
    attributes:
      label: Description
      description: Describe the user story
      placeholder: As a user, I would like to ...

  - type: textarea
    id: detail
    validations:
      required: false
    attributes:
      label: "(Optional): Provide any additional details"
      placeholder: |
        In particular I would like to be able to ...
        - Do this
        - And that
        - Maybe also this

  - type: textarea
    id: acceptance
    validations:
      required: true
    attributes:
      label: Acceptance Criteria
      description: Please specify the acceptance criteria of this user story
      placeholder: As a user, I am able to sucessfully ...
        
  - type: checkboxes
    id: seen-existing-user-stories
    attributes:
      label: Please confirm you have checked for similar existing user stories
      options:
        - label: I have confirmed there are no similar existing user stories.
          required: true
